/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/voices': typeof VoicesRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/voices': typeof VoicesRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/voices': typeof VoicesRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/doctor' | '/series' | '/settings' | '/voices' | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctor' | '/series' | '/settings' | '/voices' | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/series'
    | '/settings'
    | '/voices'
    | '/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRoute
  SeriesRoute: typeof SeriesRoute
  SettingsRoute: typeof SettingsRoute
  VoicesRoute: typeof VoicesRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRoute,
  SeriesRoute: SeriesRoute,
  SettingsRoute: SettingsRoute,
  VoicesRoute: VoicesRoute,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
